### ISSUE TITLE
return better error on Unlock/Trylock race

### ISSUE THREAD

**Issue by nightlyone** [nightlyone/lockfile#14]
The motivation for the pull-request https://github.com/nightlyone/lockfile/pull/13 from @yqylovy described an interesting observation:

> when process is executing the TryLock() and another process Unlock(),the process will return a no such file or directory error

It should return a specific error here and suggest a retry. And maybe also suggest a retry in other places.

**Comment by nightlyone** [comment]
@yqylovy I solved it differently during a longer hacking session in https://github.com/nightlyone/lockfile/pull/15

Unfortunately I had trouble reproducing that situation. 

I think I have resolved the race you observed by two independent counter measures:
* `Unlock` now only locks, where the process id is still correct and reporting an error, if it is not correct.
 see https://github.com/nightlyone/lockfile/blob/master/lockfile.go#L154 and watch out for 'ErrRogueDeletion' errors appearing. They should only be seen, if something deletes our lock files and your locking would be basically not existing when this happens (rogue sysadmin? rogue cleanup script?).
* `TryLock` suggests a retry, if something deleted a lock file just before it would return the lock as taken. see https://github.com/nightlyone/lockfile/blob/master/lockfile.go#L115

**Comment by yqylovy** [comment]
Hi @nightlyone ,I no login everyday, and saw your soluction just now. Using  a special error is a great idea and more customable .
for the reproducting, I had delete the code but I can describe how to .I just run a lot of gothread to Lock and Unlock randomly like below,as it is run in one cpu, so it's more likely to be interrrupt after file deleted .

```
for {
   go func(){
       Lock()
       Unlock()
   }()
}
```

Hope it help.
