### ISSUE TITLE
Automatic retries

### ISSUE THREAD

**Issue by timmartin19** [nightlyone/lockfile#16]
Have you considered adding automatic retries when obtaining the lock?  I feel like it's a common enough use case where you want to wait for another process to finish before you try to access the lock.  Personally, I would see it as a separate function (maybe `RetryLock(retries int, sleep time.Duration)`)

**Comment by nightlyone** [comment]
Hi @timmartin19 ,  I actually considered it while writing this library, but later removed it from the scope. I feel there are much better libraries that focus on the problem of retries using exponential back off or something simpler. Many situations also require waiting on multiple things are once. All this complexity would be a huge burden on this smallish library and can easily added from the outside using the TryLock method as needed.
