### ISSUE TITLE
Stop file from being deleted (win, mac, linux)

### ISSUE THREAD

**Issue by pjebs** [nightlyone/lockfile#26]
Can this library be used to prevent an external program from deleting or modifying an external program while I try and run the external program using `os.Exec()`?

**Comment by nightlyone** [comment]
> Can this library be used to prevent an external program from deleting or modifying an external program while I try and run the external program using os.Exec()?

hi @pjebs if any such external program would cooperate in the same way by using exactly the same mechanism as this library or even use the library, then yes. Otherwise not.

You probably want to hold different locks on that program or rely on your operation system to do that.
