### ISSUE TITLE
circular imports not allowed

### ISSUE THREAD

**Issue by OfekShochat** [nightlyone/lockfile#35]
hello, this is probably because of my inexperience with go, but when I do ```go get github.com/nightlyone/lockfile``` it says ```package github.com/nightlyone/lockfile
        imports github.com/nightlyone/lockfile: import cycle not allowed```
thanks aot

**Comment by nightlyone** [comment]
@OfekShochat could you share a gist snipped with a go.mod file where you observe this? I am currently not able to reproduce this.

**Comment by OfekShochat** [comment]
@nightlyone go.mod
```
module github.com/nightlyone/lockfile

go 1.16

require github.com/Tilps/chess v0.0.0-20200409092358-c35715299813
```
on appveyor it works. something in my setup doesn't I'm really new to it. (yesterday, I'm trying to contribute to lc0)

**Comment by nightlyone** [comment]
I think I got it: 
```
module github.com/OfekShochat/yourproject

go 1.16

require github.com/Tilps/chess v0.0.0-20200409092358-c35715299813
require github.com/nightlyone/lockfile v1.0.0
```
would be a valid go.mod file.

**Comment by OfekShochat** [comment]
i really dont know why, but when I apt get it on Linux, it works. will try this later thank you!
